---
title: Nayadotcom
timezone: UTC
collections:
  my_tags:
    title: My Tags
    output: true
    permalink: "/tag/:slug/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: my_tags
  values:
    layout: articles_by_tag
blog_theme: light
name: Naya Moll
paginate: 25
url: 
about_enabled: true
discus_identifier: chalk-1
ga_analytics: UA-28631876-6
local_fonts: true
rss_enabled: false
scrollappear_enabled: true
tag_nav_enabled: false
theme_toggle: false
social:
  dribbble: nielsenramon
  facebook: 
  flickr: 
  github: nielsenramon
  linkedin: 
  twitter: nielsenramon
  email: 
  bitcoin: 
  ethereum: 
  gitlab: 
  youtube: 
  twitch: 
  discord: 
  tumblr: 
  bitbucket: 
  docker: 
  instagram: 
  keybase: 
  medium: 
  spotify: 
  stackoverflow: 
  steam: 
assets:
  plugins:
    css:
      autoprefixer: {}
    img:
      optim: {}
  source_maps: false
  sources:
  - _assets/icons
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/yarn
exclude:
- ".travis.yml"
- bin/*
- circle.yml
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- README.md
- vendor/
- yarn.lock
plugins:
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
